# lightning.pytorch==2.0.0
seed_everything: 0
trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: 'satclip_logs'
      name: 'satclip'
      version: 'satclip'
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        save_last: True
        filename: "{epoch}-{val_loss:.2f}"
  max_epochs: 500
model:
  embed_dim: 256
  image_resolution: 256
  vision_layers: 4
  vision_width: 128
  vision_patch_size: 32
  in_channels: 4
  le_type: 'sphericalharmonics'
  frequency_num: 16
  max_radius: 0.01
  min_radius: 0.00001
  legendre_polys: 32
  sh_embedding_dims: 32
  learning_rate: 0.0001
  num_hidden_layers: 2
  capacity: 256
data:
  data_dir: /data/s2
  batch_size: 512
  num_workers: 8
  val_random_split_fraction: 0.1
watchmodel: True
